# Generated by Django 2.2.2 on 2019-06-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_remove_news_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_scrap',
            new_name='last_scrape',
        ),
    ]
