# Generated by Django 2.2.2 on 2019-06-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_auto_20190619_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='auhtor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='datemonth',
        ),
    ]
